[package]
name = "flowy-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-infra = { path = "../../../shared-lib/lib-infra" }
tokio = { version = "1.26", features = ["sync", "macros", ]}
atomic_refcell = "0.1.9"
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
rand = "0.8.5"
futures = "0.3.26"
