[package]
name = "flowy-user-deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-infra = { path = "../../../shared-lib/lib-infra" }
flowy-error  = { workspace = true }
uuid = { version = "1.3.3", features = ["v4"] }
serde.workspace = true
collab-entity = { version = "0.1.0" }
serde_json.workspace = true
serde_repr = "0.1"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
anyhow.workspace = true
tokio = { version = "1.26", features = ["sync"] }
